# Generated by Django 3.1.1 on 2021-02-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
    ]
