# Generated by Django 3.1.7 on 2021-03-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='supporting_material',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status_due',
            field=models.ManyToManyField(blank=True, related_name='test_status_due', to='users.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status_good',
            field=models.ManyToManyField(blank=True, related_name='test_status_good', to='users.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status_repeat',
            field=models.ManyToManyField(blank=True, related_name='test_status_repeat', to='users.StudentProfile'),
        ),
    ]
