# Generated by Django 3.1.1 on 2021-01-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='avg_score',
            field=models.IntegerField(default=0),
        ),
    ]
