# Generated by Django 3.1.1 on 2021-02-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210210_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='taking_category_test_bool',
            field=models.BooleanField(default=False),
        ),
    ]
