# Generated by Django 3.1.7 on 2021-03-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210324_1318'),
        ('main', '0004_auto_20210324_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
