# Generated by Django 3.1.1 on 2021-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210122_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_status_good',
        ),
        migrations.AddField(
            model_name='test',
            name='test_status_good',
            field=models.ManyToManyField(related_name='test_status_good', to='main.StudentProfile'),
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_status_new',
        ),
        migrations.AddField(
            model_name='test',
            name='test_status_new',
            field=models.ManyToManyField(related_name='test_status_new', to='main.StudentProfile'),
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_status_repeat',
        ),
        migrations.AddField(
            model_name='test',
            name='test_status_repeat',
            field=models.ManyToManyField(related_name='test_status_repeat', to='main.StudentProfile'),
        ),
    ]
