# Generated by Django 3.1.1 on 2021-01-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210122_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_repeat_due',
            field=models.IntegerField(default=6),
        ),
    ]
