# Generated by Django 3.1.1 on 2021-01-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test_test_repeat_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_status_due',
            field=models.BooleanField(default=False),
        ),
    ]
