# Generated by Django 3.1.1 on 2021-01-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_test_test_status_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_directions',
            field=models.TextField(default='Directions for the teacher - what you want the teacher to do.'),
        ),
    ]
