# Generated by Django 3.1.1 on 2021-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_test_test_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_directions',
            field=models.TextField(null=True),
        ),
    ]
