# Generated by Django 3.1.1 on 2021-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210123_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_status_due',
        ),
        migrations.AddField(
            model_name='test',
            name='test_status_due',
            field=models.ManyToManyField(related_name='test_status_due', to='main.StudentProfile'),
        ),
    ]
