# Generated by Django 3.1.1 on 2021-01-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_testorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testorder',
            old_name='test_order',
            new_name='test_bool',
        ),
    ]
