# Generated by Django 3.1.1 on 2021-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210125_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_order',
            field=models.IntegerField(default=0),
        ),
    ]
