# Generated by Django 3.1.1 on 2021-01-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_test_test_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_order',
        ),
    ]
