# Generated by Django 3.1.1 on 2021-01-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_test_test_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_order',
            field=models.IntegerField(),
        ),
    ]
