# Generated by Django 3.1.1 on 2021-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210125_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_order',
            field=models.IntegerField(unique=True),
        ),
    ]
