# Generated by Django 3.1.1 on 2021-01-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210125_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_order',
        ),
    ]
