# Generated by Django 3.1.1 on 2021-01-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_test_test_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_status_due',
            field=models.ManyToManyField(related_name='test_status_due', to='main.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status_good',
            field=models.ManyToManyField(related_name='test_status_good', to='main.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status_new',
            field=models.ManyToManyField(related_name='test_status_new', to='main.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status_repeat',
            field=models.ManyToManyField(related_name='test_status_repeat', to='main.StudentProfile'),
        ),
    ]
