# Generated by Django 3.1.1 on 2021-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_test_test_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='supporting_material',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
