# Generated by Django 3.1.1 on 2021-01-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_test_review_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=120)),
                ('body', models.TextField()),
            ],
        ),
    ]
