# Generated by Django 3.1.1 on 2021-01-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210125_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestOrder',
        ),
        migrations.RemoveField(
            model_name='test',
            name='review_questions',
        ),
    ]
